spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: animais
          uri: lb://ANIMAL-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/animal/**

        - id: ongs
          uri: lb://ONG-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/ong/**

        - id: mensagens
          uri: lb://MENSAGEM-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/mensagem/**

        - id: notificacoes
          uri: lb://NOTIFICACAO-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/notificacao/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 'http://localhost/9999'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - '*'
            allow-credentials: true
server:
  port: 9999
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      defaultZone: http://EUREKA-SERVER:8761/eureka/
springdoc:
  swagger-ui:
    urls:
      - name: animal
        url: /animal/v3/api-docs
      - name: ong
        url: /ong/v3/api-docs
      - name: mensagem
        url: /mensagem/v3/api-docs
      - name: notificacao
        url: /notificacao/v3/api-docs
