services:
  rabbit:
    image: rabbitmq:3.13-management
    container_name: RABBITMQ-SERVER
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - find_animal
  eureka:
    image: gontijojessica/eureka:latest
    container_name: EUREKA-SERVER
    ports:
      - "8761:8761"
    networks:
      - find_animal
    depends_on:
      - rabbit
  gateway:
    image: gontijojessica/gateway:latest
    container_name: GATEWAY-SERVER
    ports:
      - "9999:9999"
    networks:
      - find_animal
    depends_on:
      - ong-service
      - animal-service
      - mensagem-service
      - notificacao-service
  ong-service:
    image: gontijojessica/ong:latest
    container_name: ONG-SERVER
    networks:
      - find_animal
    depends_on:
      - rabbit
      - eureka
  animal-service:
    image: gontijojessica/animal:latest
    container_name: ANIMAL-SERVER
    networks:
      - find_animal
    depends_on:
      - rabbit
      - eureka
  mensagem-service:
    image: gontijojessica/mensagem:latest
    container_name: MENSAGEM-SERVER
    networks:
      - find_animal
    depends_on:
      - rabbit
      - eureka
  notificacao-service:
    image: gontijojessica/notificacao:latest
    container_name: NOTIFICACAO-SERVER
    networks:
      - find_animal
    depends_on:
      - rabbit
      - eureka
networks:
  find_animal:
    driver: bridge
volumes:
  rabbitmq_data: